product_list:
  path: /api/v1/products
  controller: App\Controller\ProductController::indexAction
  methods: [GET]

product_get:
  path: /api/v1/products/{id}
  controller: App\Controller\ProductController::getAction
  methods: [GET]

product_create:
  path: /api/v1/products
  controller: App\Controller\ProductController::createAction
  methods: [POST]

product_update:
  path: /api/v1/products/{idProduct}
  controller: App\Controller\ProductController:updateAction
  methods: [PATCH]
  requirements:
    idProduct: '\d+'

product_delete:
  path: /api/v1/products/{id}
  controller: App\Controller\ProductController::deleteAction
  methods: [DELETE]

customer_list:
  path: /api/v1/customers
  controller: App\Controller\CustomerController::indexAction
  methods: [GET]

customer_get:
  path: /api/v1/customers/{id}
  controller: App\Controller\CustomerController::getAction
  methods: [GET]

customer_create:
  path: /api/v1/customers
  controller: App\Controller\CustomerController::createAction
  methods: [POST]

customer_update:
  path: /api/v1/customers/{idCustomer}
  controller: App\Controller\CustomerController:updateAction
  methods: [PATCH]
  requirements:
    idCustomer: '\d+'

costumer_delete:
  path: /api/v1/customers/{id}
  controller: App\Controller\CustomerController::deleteAction
  methods: [DELETE]

cart_list:
  path: /api/v1/carts
  controller: App\Controller\CartController::indexAction
  methods: [GET]

cart_show:
  path: /api/v1/customers/{id}/cart
  controller: App\Controller\CartController::showAction
  methods: [GET]
  requirements:
    id: '\d+'

cart_create:
  path: /api/v1/carts
  controller: App\Controller\CartController::createAction
  methods: [POST]

cart_update:
  path: /api/v1/customers/{idCustomer}/cart
  controller: App\Controller\CartController:updateAction
  methods: [PATCH]
  requirements:
    idCustomer: '\d+'

cart_delete:
  path: /api/v1/customers/{idCustomer}/cart/{idCart}
  controller: App\Controller\CartController::deleteAction
  methods: [DELETE]
  requirements:
    idCustomer: '\d+'
    idCart: '\d+'