product_list:
  path: /api/v1/products
  controller: App\Controller\ProductController::indexAction
  methods: [GET]

product_get:
  path: /api/v1/products/{id}
  controller: App\Controller\ProductController::getAction
  methods: [GET]

product_create:
  path: /api/v1/products
  controller: App\Controller\ProductController::createAction
  methods: [POST]
